name: Maven build through GitHub actions

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout branch from GitHub
    - uses: actions/checkout@v3
    
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml

    - name: Step 4 - List current directory
      run: ls -a
      
