name: Master branch updated

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout branch from GitHub
      uses: actions/checkout@v3
    
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml

    - name: Step 4 - Test Results
      run: |
        # Display Surefire test results
        cat target/surefire-reports/*.txt

    - name: Step 5 - Run Code Coverage
        run: mvn jacoco:prepare-agent test jacoco:report

    - name: Step 6 - Upload Code Coverage Reports
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: target/site/jacoco/
        
