name: Master branch updated

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout branch from GitHub
      uses: actions/checkout@v3
    
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml

    - name: Step 4 - Test Results
      run: |
        # Display Surefire test results
        cat target/surefire-reports/*.txt

    - name: Step 5 - Display Test Summary
      run: |
        # Display test summary
        mvn surefire-report:report-only
        cat target/site/surefire-report.html
        
